### ISSUE TITLE
When I import datapack it says "datapack imported" and then nothing happens

### ISSUE THREAD

**Issue by ilovehorrorcats** [syldium/worldgen#30] opened 2021-12-03 22:32 UTC
Nothing happen
![sc1](https://user-images.githubusercontent.com/90423205/144681347-ddeec843-5c9d-4dd3-9024-38930f15ef46.png)
s
![sc2](https://user-images.githubusercontent.com/90423205/144681352-75b04f65-ef5a-43e3-bac6-860db242318e.png)
!
![Screenshot_20211203_163218](https://user-images.githubusercontent.com/90423205/144681585-4b1d3a96-bc54-4de0-860f-7e00ef1d8017.png)

Info:
Browser Version: Firefox 94.0 tested this on an incognito window so cache and other stuff won't effect this test

**Comment by syldium** [comment] 2021-12-04 19:27
Duplicate of #13 but thanks I was able to reproduce it with private browsing.

**Closed** 2021-12-04 20:04 UTC

**Comment by ilovehorrorcats** [comment] 2021-12-04 20:14
Its working thx for fixing it. Ive been using this tool alot
